ermap/ermap/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from flask_login import UserMixin

from ermap.database import Column, Model, SurrogatePK, db, reference_col, relationship
from ermap.extensions import bcrypt


class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        """Full user name."""
        return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({username!r})>'.format(username=self.username)

ermap/ermap/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import Form
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User


class RegisterForm(Form):
    """Register form."""

    username = StringField('Username',
                           validators=[DataRequired(), Length(min=3, max=25)])
    email = StringField('Email',
                        validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append('Username already registered')
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append('Email already registered')
            return False
        return True

ermap/ermap/__init__.py
"""Main application package."""

ermap/ermap/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""
from flask import Flask, render_template

from ermap import public, user
from ermap.assets import assets
from ermap.extensions import bcrypt, cache, db, debug_toolbar, login_manager, migrate
from ermap.settings import ProdConfig


def create_app(config_object=ProdConfig):
    """An application factory, as explained here: http://flask.pocoo.org/docs/patterns/appfactories/.

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    """Register Flask extensions."""
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    return None


def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    return None


def register_errorhandlers(app):
    """Register error handlers."""
    def render_error(error):
        """Render error template."""
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template('{0}.html'.format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

ermap/ermap/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

ermap/ermap/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """List members."""
    return render_template('users/members.html')

ermap/ermap/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

ermap/ermap/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Dmitry Kulikov</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:jubbon@yandex.ru">Contact</a></li>
    </ul>
  </small>
</footer>

ermap/ermap/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" ng-app="ermapApp"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}
  
    Нижегородская область
  
    {% endblock %}
  </title>
  <base href="/">
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome/css/font-awesome.min.css') }}">
  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}
  <!-- Яндекс.Карты -->
  <script src="http://api-maps.yandex.ru/2.0/?load=package.map&lang=ru-RU" type="text/javascript"></script>
  <!-- Google.Maps -->
  <script src="http://maps.google.com/maps/api/js?v=3.2&sensor=false"></script>

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{#% include "nav.html" %#}
{% endwith %}

    {% block content %}{% endblock %}

{#% include "footer.html" %#}

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter35192030 = new Ya.Metrika({
                        id:35192030,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true
                    });
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = "https://mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/35192030" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</body>
</html>

ermap/ermap/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}">

      ER-map

    </a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('public.home') }}">Home</a></li>
      <li><a href="{{ url_for('public.about') }}">About</a></li>
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
        <li>
            <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a></p>
        </li>
        <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>

    </ul>
    {% elif form %}
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{{ url_for('public.register') }}">Create account</a></li>
    </ul>
    <form id="loginForm" method="POST" class="navbar-form form-inline navbar-right" action="/" role="login">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.username(placeholder="Username", class_="form-control") }}
        {{ form.password(placeholder="Password", class_="form-control") }}
      </div>
      <button type="submit" class="btn btn-default">Log in</button>
    </form>
    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

ermap/ermap/templates/partials/marker.html
{% raw %}
<div ng-controller="MarkerController">
    <div class="form-group">
    <ng-form name="markerForm" ng-show="model">
        <uib-tabset vertical="true" type="pills">
            <uib-tab heading="Описание">
                <div class="marker-container">
                        <div ng-show="model">
                        <b>{{ model.published_date | date: "d.MM.yyyy 'в' HH:mm"}}</b>
                        пользователь <b>{{ model.owner }}</b> сообщил:
                        </div>
                        <textarea ng-model="model.desc" rows="4" style="resize:none" class="form-control custom-control"/>
                </div>
            </uib-tab>

            <uib-tab heading="Изображения ({{slides.length}})">
                <div class="marker-container">
                    <ul rn-carousel rn-carousel-controls rn-carousel-index="carouselIndex" rn-carousel-buffered class="carousel1">
                        <li ng-repeat="slide in slides track by slide.id" ng-class="'id-' + slide.id">
                            <div ng-style="{'background-image': 'url(' + slide.img + ')'}" ng-dblClick="open(slide.origin)" class="bgimage">
                                #{{ slide.id }}
                            </div>
                        </li>
                    </ul>
                </div>
            </uib-tab>

            <uib-tab heading="Добавить">
                <div class="marker-container">
                    <img ng-show="markerForm.file.$valid" ngf-thumbnail="obj.upload_images[0]" class="thumbnail">
                    <input type="file"
                         ngf-select
                         ng-model="obj.upload_images"
                         name="file"
                         ngf-multiple="true"
                         ngf-pattern="'image/*'"
                         ngf-accept="'image/*'"
                         ngf-max-size="20MB">
                    </input>
                    <!-- <button ng-click="obj.image = null" ng-show="obj.image">Удалить</button> -->
                </div>
            </uib-tab>
        </uib-tabset>

        <button type="button" class="btn btn-primary" ng-click="submit()">OK</button>
        <button type="button" class="btn btn-primary" ng-click="cancel()">Отмена</button>

        <div class="btn-group pull-right" uib-dropdown dropdown-append-to-body>
            <button id="btn-append-to-body" type="button" class="btn" uib-dropdown-toggle>
            <i class="fa fa-map-marker fa-fw"></i> Маркер <span class="caret"></span>
            </button>
            <ul uib-dropdown-menu role="menu" aria-labelledby="btn-append-to-body">
                <li role="menuitem">
                    <a href="#">
                        <div ng-click="setColor('red')"><i class="fa fa-circle fa-fw" style="color:red;"></i>&nbsp;</div>
                    </a>
                </li>
                <li role="menuitem">
                    <a href="#">
                        <div ng-click="setColor('yellow')"><i class="fa fa-circle fa-fw" style="color:yellow;"></i>&nbsp;</div>
                    </a>
                </li>
                <li role="menuitem">
                    <a href="#">
                        <div ng-click="setColor('green')"><i class="fa fa-circle fa-fw" style="color:green;"></i>&nbsp;</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li role="menuitem">
                    <a href="#"><div ng-show="model.status=='not_active'" ng-click="setStatus('active')">Восстановить</div></a>
                    <a href="#"><div ng-show="model.status=='active'" ng-click="setStatus('not_active')">Удалить</div></a>
                </li>
            </ul>
        </div>
    </ng-form>
    </div>
</div>
{% endraw %}

ermap/ermap/templates/partials/popup.html
{% raw %}
<div ng-controller="MarkerController">
    <div>Событие №{{ model.event_id }}</div>
    <div>Пользователь: {{ model.owner }}</div>
    <div>Дата: {{ model.published_date | date: "d.MM.yyyy HH:mm"}}</div>
    <div>Выборы: {{ (model.election_type | election_as_string) || "не заданы" }}</div>
    <div>Округи: {{ (model.group | group_as_string) || "не заданы" }}</div>
    <div>Партия: {{ (model.party | party_as_string) || "не задана" }}</div>
    <div>Событие: {{ ((model.subtype || model.type) | type_as_string) || "не задано" }}</div>
    <div ng-if="model.desc">&nbsp;</div>
    <div ng-if="model.desc">{{ model.desc }}</div>
</div>
{% endraw %}

ermap/ermap/templates/users/members.html
{% extends "layout.html" %}
{% block content %}
    <h1>Welcome {{ session.username }}</h1>
    <h3>This is the members-only page.</h3>
{% endblock %}